#! /usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
n <- 5 # default value

if(length(args) > 0)
  n <- as.integer(args[[1]])

f <- file("stdin")
lines <- readLines(f)
words <- tolower(unlist(strsplit(lines, "\\W+")))
counts <- sort(table(words), decreasing = TRUE)
counts_n <- counts[1:n]
cat(sprintf("%7d %s\n", counts_n, names(counts_n)), sep = "")
close(f)
